// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABCe_n97Jm-soAkL9SMGYrb64mLx26_dU',
    appId: '1:78702648529:web:b843e6d8c736003ab7b9f0',
    messagingSenderId: '78702648529',
    projectId: 'nyasa-acc',
    authDomain: 'nyasa-acc.firebaseapp.com',
    storageBucket: 'nyasa-acc.appspot.com',
    measurementId: 'G-T79ZLCKS69',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByIbFajBvGFnAiyMVwVXF6uBpJxf7tVjU',
    appId: '1:78702648529:android:1af302cdefa374a7b7b9f0',
    messagingSenderId: '78702648529',
    projectId: 'nyasa-acc',
    storageBucket: 'nyasa-acc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzZhWf_7cTdulxc3rpiW1_k7pjus_1zAA',
    appId: '1:78702648529:ios:046d20834d6e094eb7b9f0',
    messagingSenderId: '78702648529',
    projectId: 'nyasa-acc',
    storageBucket: 'nyasa-acc.appspot.com',
    iosClientId: '78702648529-f1hfkgb0l8elmdnbtdjurolg4vgn6o6n.apps.googleusercontent.com',
    iosBundleId: 'com.example.nyasaAcc2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzZhWf_7cTdulxc3rpiW1_k7pjus_1zAA',
    appId: '1:78702648529:ios:a1c63b83300581eab7b9f0',
    messagingSenderId: '78702648529',
    projectId: 'nyasa-acc',
    storageBucket: 'nyasa-acc.appspot.com',
    iosClientId: '78702648529-rivcern140uk2riiausq28591bo90ob6.apps.googleusercontent.com',
    iosBundleId: 'com.example.nyasaAcc2.RunnerTests',
  );
}
